### ISSUE TITLE
What does the Normalizer mean?

### ISSUE THREAD

**Issue by Kihy** [dongtsi/TrafficManipulator#1]
In main.py one of the required argument is normalizer. What is it exactly and how can I generate such a file?

**Comment by dongtsi** [comment]
Briefly, use `python tools.py` to generate the `normalizer.pkl`.
`normalizer` is a special argument needed for Kitsune. 
As Kitsune is an online NIDS dealing with streaming traffic, its normalization of features is different from offline data (MIN and MAX features' values may be updated all the time).  
To be fair, we simulate this normalization for each mutated feature.
That's why we need this special argument for Kitsune.
