### ISSUE TITLE
What is malicious traffic? 

### ISSUE THREAD

**Issue by soheejun** [dongtsi/TrafficManipulator#2]
What is malicious traffic? 

Is the malicious traffic (e.g test.pcap in example folder) which is be mutated includes only packets that sent by the attacker? 

In the case of kitsune dataset (SSDP flood, Botnet), it has the label of each packet,
so, the malicious traffic is,  
1. the set of packets that only labeled as "attack"  or, 
2. the set of packets that when the attack is started and ended (include other benign packets) 

I'm very interested in your paper, Thanks.

**Comment by dongtsi** [comment]
1. It's true in most cases, but it also depends on the attacker's ability. For example, in C2 communication, both client and server are under control by the attacker, so bidirectional traffic can be mutated.
2. From the attacker's perspective, we have no idea of which packets are exactly "malicious" or "benign" labeled by the targetted classifier (since our attack is black-box). Indeed, there is some benign traffic mixed in the attack traffic, but it is meaningless and labor-intensive to filter out the benign traffic. So the answer of your second question is "2. the set of packets that when the attack is started and ended (include other benign packets)"

(BTW, we are organizing the new version of TrafficManipulator which is more efficient and supports mutating unidirectional traffic. It will be released soon. Thx for your attention)

**Comment by yangfar** [comment]
Excuse me, has the new version been released?

**Comment by dongtsi** [comment]
Sorry for not having time to handle this now...

> Excuse me, has the new version been released?
